- name: Install go
  community.general.homebrew:
    name: go

- name: Install vim plugin
  ansible.builtin.git:
    repo: https://github.com/fatih/vim-go.git
    dest: ~/.vim/bundle/vim-go
    force: true
