- name: Install logi-options+ peripheral software
  community.general.homebrew_cask:
    name: logi-options+
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install balenaetcher bootable USB creator
  community.general.homebrew_cask:
    name: balenaetcher
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install testdisk data recovery tool
  community.general.homebrew:
    name: testdisk

- name: Install stats system monitor
  community.general.homebrew_cask:
    name: stats
