- name: Install brew versions tap
  shell: /usr/local/bin/brew tap homebrew/cask-versions

- name: Install bash-completion
  homebrew: name=bash-completion

- name: Setup bash-completion
  blockinfile:
    create: yes
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK (BASH_COMPLETION)"
    block: |
      if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
      fi

- name: Install tmux terminal multiplexer
  homebrew: name=tmux

- name: Install Midnight Commander command line file manager
  homebrew: name=midnight-commander

- name: Install icdiff side-by-side diff tool
  homebrew: name=icdiff

- name: Install telnet
  homebrew: name=telnet

- name: Install HTTPie cURL wrapper
  homebrew: name=httpie

- name: Install Alfred productivity utility
  homebrew_cask: name=alfred

- name: Install Dropbox for online storage
  homebrew_cask: name=dropbox

- name: Install FUSE for extending native file handling capabilities
  homebrew_cask: name=osxfuse

- name: Install FUSE NTFS support
  homebrew: name=ntfs-3g

- name: Install mounty for NTFS volumes
  homebrew_cask: name=mounty

- name: Install RDC
  homebrew_cask: name=microsoft-remote-desktop-beta

- name: Add /usr/local/sbin to path
  lineinfile: path=/etc/paths line='/usr/local/sbin' insertbefore='/usr/sbin'
  become: yes

- name: Add drivers brew tap
  shell: /usr/local/bin/brew tap homebrew/cask-drivers

- name: Install logitech options software
  homebrew_cask: name=logitech-options

- name: Install watch for repeating command line commands
  homebrew: name=watch

- name: Install fuse for additional file system support
  homebrew_cask: name=osxfuse

- name: Install ext4 file system support
  homebrew: name=ext4fuse

- name: Install The Unarchiver
  homebrew_cask: name=the-unarchiver

- name: Install App Cleaner
  homebrew_cask: name=appcleaner

- name: Install flycut clipboard manager
  homebrew_cask: name=flycut

- name: Install VMWare Fusion
  homebrew_cask: name=vmware-fusion

- name: Install VMWare VMDK Mounter
  homebrew_cask: name=paragon-vmdk-mounter

- name: Install Disk Inventory X
  homebrew_cask: name=disk-inventory-x

- name: Start tmux by default in Terminal.app
  blockinfile:
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK (tmux start)"
    block: |
      [[ $TERM != "screen" ]] && exec tmux

- name: Install core GNU utilities
  homebrew: name=coreutils

- name: Install balena etcher bootable USB creator
  homebrew_cask: name=balenaetcher
