- name: Install logitech options software
  homebrew_cask: name=logitech-options

- name: Install balena etcher bootable USB creator
  homebrew_cask: name=balenaetcher

- name: Install testdisk
  homebrew: name=testdisk

- name: System monitor for the menu bar
  homebrew_cask: name=stats

- name: Install OpenVPN Connect
  homebrew_cask: name=openvpn-connect
