- name: Install logitech options software
  community.general.homebrew_cask:
    name: logitech-options

- name: Install balena etcher bootable USB creator
  community.general.homebrew_cask:
    name: balenaetcher

- name: Install testdisk
  community.general.homebrew:
    name: testdisk

- name: System monitor for the menu bar
  community.general.homebrew_cask:
    name: stats

- name: Install OpenVPN Client
  community.general.homebrew_cask:
    name: tunnelblick

- name: Install ExpressVPN
  community.general.homebrew_cask:
    name: expressvpn
