---
node_version: "22.14.0"
node_npm_global_packages:
  - electron-packager
  - gitinspector
  - git-stats-html
  - markdown2confluence-cws
  - js-beautify
  - "@action-validator/core"
  - "@action-validator/cli"
  - md-to-pdf
