- name: Install lynx text-based web browser
  community.general.homebrew:
    name: lynx

- name: Install google-chrome web browser
  community.general.homebrew_cask:
    name: google-chrome

- name: Install brave-browser web browser
  community.general.homebrew_cask:
    name: brave-browser
