- name: Install franz for aggregating messaging platforms
  community.general.homebrew_cask:
    name: franz

- name: Install zoom for internet telephony
  community.general.homebrew_cask:
    name: zoom

- name: Install lynx command line browser
  community.general.homebrew:
    name: lynx

- name: Install Chrome browser
  community.general.homebrew_cask:
    name: google-chrome

- name: Install Brave browser
  community.general.homebrew_cask:
    name: brave-browser
