- name: Install jenv java environment manager
  community.general.homebrew:
    name: jenv

- name: Configure jenv shell integration
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR JENV"
    mode: "0644"
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"

- name: Install temurin JDK distribution
  community.general.homebrew_cask:
    name: temurin
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install temurin JDK distribution 21
  community.general.homebrew_cask:
    name: temurin@21
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install corretto JDK distribution 21
  community.general.homebrew_cask:
    name: corretto@21
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install visualvm JVM profiler
  community.general.homebrew_cask:
    name: visualvm

- name: Install gradle build tool
  community.general.homebrew:
    name: gradle

- name: Install gng tap for Gradle Native Generator
  community.general.homebrew_tap:
    name: gdubw/gng

- name: Install gng Gradle Native Generator
  community.general.homebrew:
    name: gng

- name: Install mvnvm maven version manager
  community.general.homebrew:
    name: mvnvm

- name: Install vim-gradle vim plugin
  ansible.builtin.git:
    repo: https://github.com/tfnico/vim-gradle.git
    dest: ~/.vim/bundle/vim-gradle
    force: true
